// @ts-nocheck
/// <reference types='vitest' />
import { describe, it, expect, beforeEach } from 'vitest';
import { PdfExportService, PdfExportOptions } from '../pdf-export.service';
import { ColDef } from '../models';

describe('PdfExportService', () => {
  let service: PdfExportService;

  const mockColumnDefs: ColDef[] = [
    { field: 'id', headerName: 'ID' },
    { field: 'name', headerName: 'Name' },
    { field: 'age', headerName: 'Age' },
  ];

  const mockRowData = [
    { id: 1, name: 'Alice', age: 25 },
    { id: 2, name: 'Bob', age: 30 },
    { id: 3, name: 'Charlie', age: 35 },
  ];

  beforeEach(() => {
    service = new PdfExportService();
  });

  it('should be created', () => {
    expect(service).toBeTruthy();
  });

  describe('PDF Export Options', () => {
    it('should use default options', () => {
      // Test that service has method (actual PDF generation requires jsPDF)
      expect(service).toBeDefined();
    });
  });

  describe('Export Configuration', () => {
    it('should accept custom file name', () => {
      const options: PdfExportOptions = { fileName: 'custom.pdf' };
      expect(options.fileName).toBe('custom.pdf');
    });

    it('should accept landscape orientation', () => {
      const options: PdfExportOptions = { orientation: 'landscape' };
      expect(options.orientation).toBe('landscape');
    });

    it('should accept page size', () => {
      const options: PdfExportOptions = { pageSize: 'a3' };
      expect(options.pageSize).toBe('a3');
    });

    it('should accept column keys filter', () => {
      const options: PdfExportOptions = { columnKeys: ['id', 'name'] };
      expect(options.columnKeys).toEqual(['id', 'name']);
    });

    it('should accept custom title', () => {
      const options: PdfExportOptions = { title: 'My Report' };
      expect(options.title).toBe('My Report');
    });

    it('should accept footer text', () => {
      const options: PdfExportOptions = { footerText: 'Generated by db-grid' };
      expect(options.footerText).toBe('Generated by db-grid');
    });

    it('should accept show page number option', () => {
      const options: PdfExportOptions = { showPageNumber: false };
      expect(options.showPageNumber).toBe(false);
    });

    it('should accept table theme', () => {
      const options: PdfExportOptions = { tableTheme: 'grid' };
      expect(options.tableTheme).toBe('grid');
    });

    it('should accept custom colors', () => {
      const options: PdfExportOptions = {
        stripeColor: [220, 220, 220] as [number, number, number],
        headerBackgroundColor: [0, 0, 128] as [number, number, number],
        headerTextColor: [255, 255, 255] as [number, number, number],
      };
      expect(options.stripeColor).toEqual([220, 220, 220]);
      expect(options.headerBackgroundColor).toEqual([0, 0, 128]);
      expect(options.headerTextColor).toEqual([255, 255, 255]);
    });
  });

  describe('Column Filtering', () => {
    it('should filter columns by columnKeys', () => {
      const filteredCols = mockColumnDefs.filter(c => {
        const col = c;
        return !col.hide && col.field;
      });
      expect(filteredCols.length).toBe(3);
    });
  });

  describe('Data Processing', () => {
    it('should map row data to columns', () => {
      const exportCols = mockColumnDefs.filter(c => !c.hide && c.field);
      const body = mockRowData.map(row =>
        exportCols.map(col => row[col.field as string])
      );
      expect(body).toHaveLength(3);
    });

    it('should handle nested field paths', () => {
      const nestedData = { user: { name: 'John' } };
      const getCellValue = (row: any, field: string) => {
        if (!field || !row) return null;
        const keys = field.split('.');
        let value = row;
        for (const key of keys) {
          if (value == null) return null;
          value = value[key];
        }
        return value;
      };
      expect(getCellValue(nestedData, 'user.name')).toBe('John');
    });

    it('should apply valueFormatter if present', () => {
      const col = { 
        field: 'age', 
        valueFormatter: (params: any) => params.value + ' years' 
      };
      const value = 25;
      const formatted = col.valueFormatter({ value, data: {}, colDef: col });
      expect(formatted).toBe('25 years');
    });
  });
});