name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "20"

    - name: Clean install
      run: rm -rf node_modules package-lock.json dist && npm install --force

    - name: Build Demo
      run: npx ng build --configuration production

    - name: Deploy to GitHub Pages
      if: github.ref == "refs/heads/master"
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: dist/db-grid/browser
        clean: true
        token: ${{ secrets.ACCESS_TOKEN }}
        git-config-name: github-actions[bot]
        git-config-email: github-actions[bot]@users.noreply.github.com
        commit-message: "Deploy from ${{ github.sha }} [nocache]"
